import { Category, Product, Order, Quote, Booking, Review, StoreSettings, AuditLogEntry } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_suits',
    name: 'Suits',
    slug: 'suits',
    description: 'Two-piece and three-piece bespoke and ready-to-wear tailored suits for weddings and executive elegance.',
    image_path: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    sort_order: 1,
    is_visible: true,
  },
  {
    id: 'cat_blazers',
    name: 'Blazers & Jackets',
    slug: 'blazers-jackets',
    description: 'Versatile statement blazers, velvet dinner jackets, and precision single-breasted coats.',
    image_path: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
    sort_order: 2,
    is_visible: true,
  },
  {
    id: 'cat_tuxedos',
    name: 'Tuxedos',
    slug: 'tuxedos',
    description: 'Impeccable black tie and red carpet tuxedos with satin lapels and hand-finished accents.',
    image_path: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=800&q=80',
    sort_order: 3,
    is_visible: true,
  },
  {
    id: 'cat_shirts',
    name: 'Shirts',
    slug: 'shirts',
    description: 'Crisp Egyptian and Italian cotton dress shirts crafted for peak comfort and breathability.',
    image_path: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
    sort_order: 4,
    is_visible: true,
  },
  {
    id: 'cat_pants',
    name: 'Pants',
    slug: 'pants',
    description: 'Hand-tailored formal trousers with side adjusters and sharp front creases.',
    image_path: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
    sort_order: 5,
    is_visible: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_crystal_three_piece',
    category_id: 'cat_suits',
    name: 'Crystal-Trim Three-Piece Suit',
    slug: 'crystal-trim-three-piece-suit',
    description: 'Luxurious bespoke three-piece suit featuring handcrafted crystal-beaded peak lapel trims, double-breasted vest, and tailored trousers. Crafted in Ijebu-Ode for high-society weddings and galas.',
    price_kobo: 18500000, // ₦185,000
    is_bespoke: true,
    is_featured: true,
    is_visible: true,
    created_at: '2026-09-15T10:00:00Z',
    images: [
      {
        id: 'img_crys_1',
        product_id: 'prod_crystal_three_piece',
        storage_path: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
        alt: 'Crystal-Trim Three-Piece Suit front profile',
        sort_order: 1,
        is_cover: true,
      },
      {
        id: 'img_crys_2',
        product_id: 'prod_crystal_three_piece',
        storage_path: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=800&q=80',
        alt: 'Crystal lapel and waistcoat craftsmanship detail',
        sort_order: 2,
        is_cover: false,
      },
    ],
    variants: [
      { id: 'var_crys_38', product_id: 'prod_crystal_three_piece', size_label: '38R', sku: 'APF-CRY-38R', stock: 4 },
      { id: 'var_crys_40', product_id: 'prod_crystal_three_piece', size_label: '40R', sku: 'APF-CRY-40R', stock: 6 },
      { id: 'var_crys_42', product_id: 'prod_crystal_three_piece', size_label: '42R', sku: 'APF-CRY-42R', stock: 5 },
      { id: 'var_crys_44', product_id: 'prod_crystal_three_piece', size_label: '44R', sku: 'APF-CRY-44R', stock: 3 },
      { id: 'var_crys_46', product_id: 'prod_crystal_three_piece', size_label: '46R', sku: 'APF-CRY-46R', stock: 2 },
      { id: 'var_crys_cust', product_id: 'prod_crystal_three_piece', size_label: 'Custom Made-to-Measure', sku: 'APF-CRY-BESPOKE', stock: 50 },
    ],
  },
  {
    id: 'prod_navy_executive',
    category_id: 'cat_suits',
    name: 'Navy Executive Three-Piece Suit',
    slug: 'navy-executive-three-piece-suit',
    description: 'The quintessential boardroom power suit in deep midnight navy Super 150s wool blend. Includes single-breasted two-button jacket, tailored waistcoat, and flat-front trousers.',
    price_kobo: 15000000, // ₦150,000
    is_bespoke: false,
    is_featured: true,
    is_visible: true,
    created_at: '2026-09-18T11:00:00Z',
    images: [
      {
        id: 'img_navy_1',
        product_id: 'prod_navy_executive',
        storage_path: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
        alt: 'Navy Executive Three-Piece suit',
        sort_order: 1,
        is_cover: true,
      },
    ],
    variants: [
      { id: 'var_navy_38', product_id: 'prod_navy_executive', size_label: '38R', sku: 'APF-NVY-38R', stock: 8 },
      { id: 'var_navy_40', product_id: 'prod_navy_executive', size_label: '40R', sku: 'APF-NVY-40R', stock: 12 },
      { id: 'var_navy_42', product_id: 'prod_navy_executive', size_label: '42R', sku: 'APF-NVY-42R', stock: 10 },
      { id: 'var_navy_44', product_id: 'prod_navy_executive', size_label: '44R', sku: 'APF-NVY-44R', stock: 5 },
      { id: 'var_navy_cust', product_id: 'prod_navy_executive', size_label: 'Custom Made-to-Measure', sku: 'APF-NVY-BESPOKE', stock: 50 },
    ],
  },
  {
    id: 'prod_modern_two_tone',
    category_id: 'cat_blazers',
    name: 'Modern Classic Two-Tone Blazer',
    slug: 'modern-classic-two-tone-blazer',
    description: 'Striking contrast lapel blazer combining deep navy body with warm camel peak lapels. Tailored with kissing horn buttons and structured natural shoulders.',
    price_kobo: 9500000, // ₦95,000
    is_bespoke: false,
    is_featured: true,
    is_visible: true,
    created_at: '2026-09-20T09:30:00Z',
    images: [
      {
        id: 'img_two_1',
        product_id: 'prod_modern_two_tone',
        storage_path: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=80',
        alt: 'Modern Classic Two-Tone Blazer',
        sort_order: 1,
        is_cover: true,
      },
    ],
    variants: [
      { id: 'var_two_40', product_id: 'prod_modern_two_tone', size_label: '40R', sku: 'APF-2T-40R', stock: 7 },
      { id: 'var_two_42', product_id: 'prod_modern_two_tone', size_label: '42R', sku: 'APF-2T-42R', stock: 9 },
      { id: 'var_two_44', product_id: 'prod_modern_two_tone', size_label: '44R', sku: 'APF-2T-44R', stock: 4 },
    ],
  },
  {
    id: 'prod_royal_purple_tux',
    category_id: 'cat_tuxedos',
    name: 'Royal Purple Tuxedo Set',
    slug: 'royal-purple-tuxedo-set',
    description: 'Show-stopping rich royal purple tuxedo with deep black satin shawl lapels and matching silk accessories. An exquisite choice for grooms and gala headliners.',
    price_kobo: 21000000, // ₦210,000
    is_bespoke: true,
    is_featured: true,
    is_visible: true,
    created_at: '2026-09-22T14:00:00Z',
    images: [
      {
        id: 'img_purple_1',
        product_id: 'prod_royal_purple_tux',
        storage_path: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=800&q=80',
        alt: 'Royal Purple Tuxedo Set',
        sort_order: 1,
        is_cover: true,
      },
    ],
    variants: [
      { id: 'var_purp_38', product_id: 'prod_royal_purple_tux', size_label: '38R', sku: 'APF-PUR-38R', stock: 3 },
      { id: 'var_purp_40', product_id: 'prod_royal_purple_tux', size_label: '40R', sku: 'APF-PUR-40R', stock: 5 },
      { id: 'var_purp_42', product_id: 'prod_royal_purple_tux', size_label: '42R', sku: 'APF-PUR-42R', stock: 4 },
      { id: 'var_purp_cust', product_id: 'prod_royal_purple_tux', size_label: 'Custom Made-to-Measure', sku: 'APF-PUR-BESPOKE', stock: 30 },
    ],
  },
  {
    id: 'prod_emerald_velvet',
    category_id: 'cat_blazers',
    name: 'Emerald Velvet Dinner Jacket',
    slug: 'emerald-velvet-dinner-jacket',
    description: 'Sumptuous plush velvet in imperial emerald green with black grosgrain shawl collar. Perfect for evening banquets and red-carpet ceremonies.',
    price_kobo: 13500000, // ₦135,000
    is_bespoke: false,
    is_featured: false,
    is_visible: true,
    created_at: '2026-09-24T12:00:00Z',
    images: [
      {
        id: 'img_emerald_1',
        product_id: 'prod_emerald_velvet',
        storage_path: 'https://images.unsplash.com/photo-1555069519-127aadedf1ee?auto=format&fit=crop&w=800&q=80',
        alt: 'Emerald Velvet Dinner Jacket',
        sort_order: 1,
        is_cover: true,
      },
    ],
    variants: [
      { id: 'var_eme_40', product_id: 'prod_emerald_velvet', size_label: '40R', sku: 'APF-EME-40R', stock: 5 },
      { id: 'var_eme_42', product_id: 'prod_emerald_velvet', size_label: '42R', sku: 'APF-EME-42R', stock: 6 },
      { id: 'var_eme_44', product_id: 'prod_emerald_velvet', size_label: '44R', sku: 'APF-EME-44R', stock: 3 },
    ],
  },
  {
    id: 'prod_ivory_groom_suit',
    category_id: 'cat_suits',
    name: 'Ivory Double-Breasted Groom Suit',
    slug: 'ivory-double-breasted-groom-suit',
    description: 'Ethereal ivory white double-breasted suit designed for the distinguished groom. Gold embossed buttons and custom monogrammed inner lining included.',
    price_kobo: 19500000, // ₦195,000
    is_bespoke: true,
    is_featured: false,
    is_visible: true,
    created_at: '2026-09-25T16:00:00Z',
    images: [
      {
        id: 'img_ivory_1',
        product_id: 'prod_ivory_groom_suit',
        storage_path: 'https://images.unsplash.com/photo-1550246140-5119ae4790b8?auto=format&fit=crop&w=800&q=80',
        alt: 'Ivory Double-Breasted Groom Suit',
        sort_order: 1,
        is_cover: true,
      },
    ],
    variants: [
      { id: 'var_ivo_40', product_id: 'prod_ivory_groom_suit', size_label: '40R', sku: 'APF-IVO-40R', stock: 4 },
      { id: 'var_ivo_42', product_id: 'prod_ivory_groom_suit', size_label: '42R', sku: 'APF-IVO-42R', stock: 5 },
      { id: 'var_ivo_cust', product_id: 'prod_ivory_groom_suit', size_label: 'Custom Made-to-Measure', sku: 'APF-IVO-BESPOKE', stock: 40 },
    ],
  },
  {
    id: 'prod_egyptian_shirt',
    category_id: 'cat_shirts',
    name: 'Egyptian Cotton French Cuff Shirt',
    slug: 'egyptian-cotton-french-cuff-shirt',
    description: 'Pure 100% long-staple Egyptian cotton shirt with structured spread collar and double French cuffs. Tailored to stay crisp all day in the Nigerian climate.',
    price_kobo: 3500000, // ₦35,000
    is_bespoke: false,
    is_featured: false,
    is_visible: true,
    created_at: '2026-09-26T08:00:00Z',
    images: [
      {
        id: 'img_shirt_1',
        product_id: 'prod_egyptian_shirt',
        storage_path: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
        alt: 'Crisp White French Cuff Shirt',
        sort_order: 1,
        is_cover: true,
      },
    ],
    variants: [
      { id: 'var_sh_15', product_id: 'prod_egyptian_shirt', size_label: '15.5 Collar (M)', sku: 'APF-SHT-155', stock: 20 },
      { id: 'var_sh_16', product_id: 'prod_egyptian_shirt', size_label: '16.0 Collar (L)', sku: 'APF-SHT-160', stock: 25 },
      { id: 'var_sh_165', product_id: 'prod_egyptian_shirt', size_label: '16.5 Collar (XL)', sku: 'APF-SHT-165', stock: 18 },
    ],
  },
  {
    id: 'prod_charcoal_trousers',
    category_id: 'cat_pants',
    name: 'Charcoal Bespoke Pleated Trousers',
    slug: 'charcoal-bespoke-pleated-trousers',
    description: 'Refined charcoal grey trousers with single forward pleats, functional side cinch adjusters, and a clean 2-inch cuff.',
    price_kobo: 4500000, // ₦45,000
    is_bespoke: false,
    is_featured: false,
    is_visible: true,
    created_at: '2026-09-27T09:00:00Z',
    images: [
      {
        id: 'img_pants_1',
        product_id: 'prod_charcoal_trousers',
        storage_path: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
        alt: 'Charcoal Bespoke Pleated Trousers',
        sort_order: 1,
        is_cover: true,
      },
    ],
    variants: [
      { id: 'var_pnt_32', product_id: 'prod_charcoal_trousers', size_label: '32 Waist', sku: 'APF-PNT-32', stock: 12 },
      { id: 'var_pnt_34', product_id: 'prod_charcoal_trousers', size_label: '34 Waist', sku: 'APF-PNT-34', stock: 15 },
      { id: 'var_pnt_36', product_id: 'prod_charcoal_trousers', size_label: '36 Waist', sku: 'APF-PNT-36', stock: 10 },
    ],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_1',
    order_number: 'APF-261001-8392',
    user_id: 'usr_tobi',
    customer_name: 'Tobi Adeleke',
    customer_email: 'tobi.adeleke@gmail.com',
    customer_phone: '+2348031234567',
    status: 'paid',
    subtotal_kobo: 18500000,
    delivery_fee_kobo: 450000,
    total_kobo: 18950000,
    currency: 'NGN',
    shipping_address: {
      fullName: 'Tobi Adeleke',
      email: 'tobi.adeleke@gmail.com',
      phone: '+2348031234567',
      address: 'Plot 14, Admiralty Way, Lekki Phase 1',
      city: 'Lekki',
      state: 'Lagos',
      country: 'Nigeria',
      deliveryOptionId: 'del_lagos_ogun',
      deliveryMethod: 'Lagos & Ogun Express Courier',
    },
    tracking_url: 'https://tracking.aplusfashion.ng/APF-261001-8392',
    internal_note: 'Groom suit for wedding in Nov. Customer requested gold hanger.',
    placed_at: '2026-10-01T14:22:00Z',
    items: [
      {
        id: 'ord_item_1',
        order_id: 'ord_1',
        product_id: 'prod_crystal_three_piece',
        variant_id: 'var_crys_40',
        name_snapshot: 'Crystal-Trim Three-Piece Suit',
        size_snapshot: '40R',
        fit_type: 'bespoke',
        unit_price_kobo: 18500000,
        qty: 1,
        line_total_kobo: 18500000,
        image_snapshot: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
      },
    ],
    payment: {
      reference: 'APF-APF-261001-8392-k1m9p',
      order_id: 'ord_1',
      provider: 'paystack',
      channel: 'card',
      amount_kobo: 18950000,
      status: 'success',
      refund_status: 'none',
      paid_at: '2026-10-01T14:24:12Z',
      created_at: '2026-10-01T14:22:10Z',
    },
  },
  {
    id: 'ord_2',
    order_number: 'APF-260928-4211',
    user_id: 'usr_chinedu',
    customer_name: 'Barrister Chinedu O.',
    customer_email: 'chinedu.law@chamber.ng',
    customer_phone: '+2348029876543',
    status: 'shipped',
    subtotal_kobo: 15000000,
    delivery_fee_kobo: 750000,
    total_kobo: 15750000,
    currency: 'NGN',
    shipping_address: {
      fullName: 'Barrister Chinedu O.',
      email: 'chinedu.law@chamber.ng',
      phone: '+2348029876543',
      address: 'Suite 3B, Federal Secretariat Complex, Shehu Shagari Way',
      city: 'Central Business District',
      state: 'Abuja',
      country: 'Nigeria',
      deliveryOptionId: 'del_nationwide',
      deliveryMethod: 'Nationwide Courier',
    },
    tracking_url: 'https://tracking.aplusfashion.ng/APF-260928-4211',
    internal_note: 'Dispatched via GIG Logistics on 30 Sep.',
    placed_at: '2026-09-28T09:40:00Z',
    items: [
      {
        id: 'ord_item_2',
        order_id: 'ord_2',
        product_id: 'prod_navy_executive',
        variant_id: 'var_navy_42',
        name_snapshot: 'Navy Executive Three-Piece Suit',
        size_snapshot: '42R',
        fit_type: 'ready_to_wear',
        unit_price_kobo: 15000000,
        qty: 1,
        line_total_kobo: 15000000,
        image_snapshot: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
      },
    ],
    payment: {
      reference: 'APF-APF-260928-4211-9x4w2',
      order_id: 'ord_2',
      provider: 'paystack',
      channel: 'bank_transfer',
      amount_kobo: 15750000,
      status: 'success',
      refund_status: 'none',
      paid_at: '2026-09-28T09:45:30Z',
      created_at: '2026-09-28T09:40:05Z',
    },
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'quote_1',
    reference: 'QT-261001-5120',
    customer_name: 'Adebayo Shonibare',
    customer_email: 'adebayo.shoni@outlook.com',
    customer_phone: '+2348123456789',
    garment: 'Bespoke 3-Piece Groom Tuxedo + 4 Groomsmen Suits',
    occasion: 'Destination Wedding in Zanzibar',
    event_date: '2026-12-14',
    budget_min_kobo: 60000000, // ₦600,000
    budget_max_kobo: 90000000, // ₦900,000
    notes: 'Looking for matching midnight navy tuxedos with champagne velvet accents for the groomsmen. Needs in-person fitting in Ijebu-Ode.',
    photo_paths: [],
    contact_preference: 'WhatsApp',
    status: 'requested',
    created_at: '2026-10-01T16:15:00Z',
  },
  {
    id: 'quote_2',
    reference: 'QT-260929-3381',
    customer_name: 'Kolawole Adeleke',
    customer_email: 'k.adeleke@energycorp.ng',
    customer_phone: '+2348077778899',
    garment: 'Double-Breasted Cashmere Blazer & Trousers',
    occasion: 'Annual Shareholders Meeting & Gala',
    event_date: '2026-10-25',
    budget_min_kobo: 15000000,
    budget_max_kobo: 22000000,
    notes: 'Premium charcoal blend with horn buttons. Please advise on fabric swatches.',
    photo_paths: [],
    contact_preference: 'Phone',
    status: 'quote_sent',
    quoted_price_kobo: 18500000,
    ready_by: '2026-10-20',
    owner_message: 'Hello Kolawole, we have selected our finest Vitale Barberis Super 130s fabric in charcoal. Price includes 1 fitting and alteration.',
    created_at: '2026-09-29T11:20:00Z',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book_1',
    reference: 'BK-261002-1204',
    customer_name: 'Babatunde Olaleye',
    customer_email: 'babatunde.ola@yahoo.com',
    customer_phone: '+2348035551212',
    type: 'video',
    starts_at: '2026-10-02T14:00:00Z',
    status: 'confirmed',
    notes: 'Client lives in Port Harcourt. Measurement tape ready at home.',
    created_at: '2026-10-01T08:30:00Z',
  },
  {
    id: 'book_2',
    reference: 'BK-261003-4419',
    customer_name: 'Emeka Kalu',
    customer_email: 'emeka.kalu@gmail.com',
    customer_phone: '+2348061112233',
    type: 'shop',
    starts_at: '2026-10-03T11:00:00Z',
    status: 'requested',
    notes: 'Traveling from Ibadan to 2 Jagunmolu St, Ijebu-Ode for wedding suit fitting.',
    created_at: '2026-10-01T15:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    product_id: 'prod_crystal_three_piece',
    product_name: 'Crystal-Trim Three-Piece Suit',
    author_name: 'Tobi Adeleke',
    author_location: 'Lagos',
    rating: 5,
    body: 'The tan three-piece fit perfectly and arrived in four days. Henry and his team delivered beyond expectations for my wedding reception.',
    status: 'approved',
    created_at: '2026-09-20T12:00:00Z',
  },
  {
    id: 'rev_2',
    product_id: 'prod_navy_executive',
    product_name: 'Navy Executive Three-Piece Suit',
    author_name: 'Barrister Chinedu O.',
    author_location: 'Abuja',
    rating: 5,
    body: 'Unmatched craftsmanship. The fabric drape and shoulder pad structure are equivalent to Savile Row, but made right here in Ogun State.',
    status: 'approved',
    created_at: '2026-09-25T14:30:00Z',
  },
  {
    id: 'rev_3',
    product_id: 'prod_royal_purple_tux',
    product_name: 'Royal Purple Tuxedo Set',
    author_name: 'Dr. Femi B.',
    author_location: 'Ibadan',
    rating: 5,
    body: 'Wore this to our annual physicians gala and received non-stop compliments all evening. The satin lapel is impeccably tailored.',
    status: 'approved',
    created_at: '2026-09-28T19:00:00Z',
  },
  {
    id: 'rev_4',
    product_id: 'prod_ivory_groom_suit',
    product_name: 'Ivory Double-Breasted Groom Suit',
    author_name: 'Emeka K.',
    author_location: 'London, UK',
    rating: 5,
    body: 'Ordered from the UK with video call measurements. Fits like a glove with zero alterations needed! Will be ordering all my formal wear from A-Plus.',
    status: 'approved',
    created_at: '2026-09-30T10:15:00Z',
  },
];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  homepage_banners: [
    {
      id: 'banner_1',
      headline: 'Wear Class, Live Bold.',
      sub: 'Tailored suits, tuxedos and blazers made to fit you — ready to wear or made to measure in Ijebu-Ode.',
      cta_label: 'Shop the collection',
      cta_href: '/shop',
      secondary_label: 'Request a quote',
      secondary_href: '/quote',
      image_path: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1600&q=85',
      visible: true,
      sort_order: 1,
    },
  ],
  about: {
    headline: 'Crafting Sartorial Distinction in Ijebu-Ode',
    story_html: 'Founded by master tailor Henry Abraham, A-Plus Fashion Home combines traditional British tailoring finesse with vibrant Nigerian flair. For over 5 years, we have outfitted grooms, executives, and international connoisseurs who refuse to compromise on fit, fabric, or finish.',
    years: 5,
    product_count: '100+',
    happy_clients: '1,200+',
  },
  contact: {
    whatsapp: '+2347071374515',
    phone: '+2347071374515',
    alt_phone: '09055080524',
    email: 'henryaplus82@gmail.com',
    address: '2 Jagunmolu Street, Ondo Road, Ijebu-Ode, Ogun State, Nigeria',
    hours: 'Mon–Sat 9:00 AM – 6:00 PM',
  },
  social: {
    instagram: 'https://instagram.com/aplusfashionhome',
    facebook: 'https://facebook.com/aplusfashionhome',
    tiktok: 'https://tiktok.com/@aplusfashionhome',
    whatsapp_channel: 'https://wa.me/2347071374515',
  },
  fx_rates: {
    USD: 1550,
    GBP: 1980,
  },
  delivery_rules: [
    { id: 'del_lagos_ogun', label: 'Lagos & Ogun Express Courier', fee_kobo: 450000, eta: '1–3 business days' },
    { id: 'del_nationwide', label: 'Nationwide Nigeria (Waybill / Courier)', fee_kobo: 750000, eta: '3–5 business days' },
    { id: 'del_pickup', label: 'Shop Pick-up (2 Jagunmolu St, Ijebu-Ode)', fee_kobo: 0, eta: 'Ready within 24 hours' },
    { id: 'del_intl', label: 'International Express (DHL Worldwide)', fee_kobo: 4500000, eta: '5–8 business days' },
  ],
};

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 1,
    actor_email: 'henryaplus82@gmail.com',
    action: 'product.create',
    entity: 'products',
    entity_id: 'prod_crystal_three_piece',
    before: null,
    after: { name: 'Crystal-Trim Three-Piece Suit', price_kobo: 18500000 },
    created_at: '2026-09-15T10:05:00Z',
  },
  {
    id: 2,
    actor_email: 'henryaplus82@gmail.com',
    action: 'order.status_update',
    entity: 'orders',
    entity_id: 'ord_2',
    before: { status: 'paid' },
    after: { status: 'shipped', tracking_url: 'https://tracking.aplusfashion.ng/APF-260928-4211' },
    created_at: '2026-09-30T10:00:00Z',
  },
];
